### ISSUE TITLE
"Default Anti-Aliasing" should be Anti-Aliasing Method

### ISSUE THREAD

**Issue by voicemxil** [biase-d/ue4cheatcreator#4]
r.DefaultFeature.AntiAliasing is currently shown as a "Default Anti-Aliasing" quality level between 0-6, which is more inline with r.PostProcessAAQuality. However this CVar is actually meant to control the method of AA: 0=off, 1=FXAA=, 2=TAA, 3=MSAA (forward only).

**Comment by biase-d** [comment]
Thanks for the info, I will update

I think I will have to go through the UE4 CVARS documentation and make sure I categorize everything accurately
